### ISSUE TITLE
Bug Minor - Specification template - Bullets and hyperlinks not being displayed 

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#266]
Hi, I have an issue where the bullets and hyperlinks are not getting displayed: 

1. Go to: https://www.macktrucks.com/trucks/terrapro-series/specs/
2. Check Engines sections
3. Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/terra-pro-series/Specs/
4. Check discrepancies for the same section
<img width="1412" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126146302/e571cee4-86c1-4f7c-a263-95dfc18ac7ce">

**Comment by Andrei-Boiangiu** [comment]
This issue might be related to not being able to add a second line of Specifications in this cases

[https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%[…]5575%7D&file=index.docx&action=default&mobileredirect=true](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB993E909-6EB8-43F1-AB6C-C5A0B1C25575%7D&file=index.docx&action=default&mobileredirect=true)

https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/md-series/Specs/


![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/8df88e96-17ad-422d-a1b4-8a8db85d3b90)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/767dc1d6-4f6a-4c91-ad97-630e383e3329)

Thus I would mark it as Major

**Comment by Andrei-Boiangiu** [comment]
The first part of the bug is confirmed as fixed with the bullet points

but the part in my above comment on the case of the line of text not being displayed in the Specification table is still present

[https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%[…]5575%7D&file=index.docx&action=default&mobileredirect=true](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB993E909-6EB8-43F1-AB6C-C5A0B1C25575%7D&file=index.docx&action=default&mobileredirect=true)

https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/md-series/Specs/

( see screenshots in the comment above)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed :

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b6a0c87b-e20d-4878-84a1-55f5bd0dd7af">
