### ISSUE TITLE
Post Live: Eloqua form to load based on cookie setting

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#415]
Need to check the oneTrust cookie setting and load the Eloqua forms on the site.
If the user has not accepted targeting cookie a message needs to be shown in the placeholder insted of the form.

Message should also contain a link to change the cookie setting.

**Comment by girishdigrajkar** [comment]
Validate this bug and able to see the form displayed in case cookies are accepted; 
When the user does not accept (targeting) cookie a message is shown in the placeholder instead of the form.

Bug #432 has been raised for related small observation related to content & major observation related to cookie triggering.
This bug could be closed.
