### ISSUE TITLE
Eloqua Form push

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#498]
Hi Manuel,

Could you please create a form with the below eloqua code and provide us the link to add to page.

[Electrifi Form Code.txt](https://github.com/hlxsites/vg-macktrucks-com/files/13206957/Electrifi.Form.Code.txt)

**Comment by BeckyMedlin** [comment]
@manuel-vara The status says "Ready for Testing," but this item is closed and #499 isn't in the project. Should it be?

**Comment by manuel-vara** [comment]
From a development workflow point of view once the issue is linked in the PR and this PR is merged then the action workflow  'closes' the issue from a development point of view b ut this is independent from project workflow where we handle the different status in the project board.
If QA finds something that needs to be fixed by developer the issue can be reopen with a comment.
