### ISSUE TITLE
FR: V2 Columns Block "Background Image" Variant

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#582]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#198  

**Agile Requirement**
As a Business Owner, I want to display an image with a card overlapping it displaying some informative text and related links so that my clients can learn more about our solutions. 

**Description**
Add a new variant to the V2 Columns Block that follows the figma design and specifications. 

**Acceptance Criteria**
1-As an editor, I can select the new variant in the V2 Columns Block. 
2- As an editor I can add an image, a title, some text, a button, a subtitle and up to 3 links. 
3- As an editor it is my responsibility to not surpass the 3 link limit.
4- The tablet solution imitates the desktop design adapting it to its size. 
5- The new variant follows the figma design for all viewports: 
[- Mobile](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-102251&mode=dev)
[- Desktop](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101545&mode=dev)
-Tablet (same as desktop)

**Comment by shirin27** [comment]
adding in screenshots of the Figma file for my reference:
![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/84500cdc-0c83-487b-9037-e9e793c55752)
![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/3430ca38-7d36-4cea-b6fc-24bf4c0bb5a2)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, closing this ticket: 

**Test Summary :**
**Desktop:**
Block height is 720px unlike 583px in figma
[SV]: I’ve looked at it, the 720px is because of the image aspect ratio. In general, a section with background image has a 2/1 aspect ratio. So this is an expected size, but not present in design yet. When the content of the card is longer, the block will be of a different size

**Mobile:**
Image height is 405px whereas as per figma it should be 270px
[SV]: As for the image size on mobile, the aspect ratio stays the same. I’ve reuploaded the image, at a 2/1 aspect ratio as agreed with the client

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e0b466a3-c9f0-49dd-b17d-aceb1a79dec4)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9d69d8c1-f1d6-4f79-b766-d723382b9e36)
