### ISSUE TITLE
FR: Solutions "icon list" V" Columns block variant

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#628]
From vg-macktrucks-com-rd created by [shirin27](https://github.com/shirin27): Netcentric/vg-macktrucks-com-rd#218  
**Description**
A variant of V2 Columns block with icons and links as a variation

**Agile Requirement**
As a user, I want to have some helpful icons so that I can easily identify the solutions MT is proposing.

**Acceptance Criteria**

- Card contains a title, descriptive text, a button, and clickable solution links in a list format with icons to the left
- All solutions with icons are oriented to the left of the text 
- Icon list is displayed below the Explore button
- The padding of the card text is consistent with other cards

**Open Questions** 

- Can the editor select from a library of icons? 
  - Yes, can be a variety of icons.
- Can we implement the icons into an existing block
  - A variant of V2 Columns block

<img width="1456" alt="Screenshot 2024-02-29 at 11 48 37" src="https://github.com/hlxsites/vg-macktrucks-com/assets/135319298/230dcf56-7436-447c-8767-dfa695b70f45">

**Comment by girishdigrajkar** [comment]
Testing summary:

**Desktop:**

1. Padding before title is 18px whereas, expected is 24px as per figma
2. The title should be displayed on 3lines whereas, in figma it is displayed on 2lines for the same text.
3. The size for block element is shown as 485 X 696.30 px whereas, as per sigma it should be 512 X 650 px
4. 4.  The pixel size length from top should be 48px whereas, it is 75px &  pixel size length at bottom should be 38px whereas, it is 85px

**Mobile:**
Button in Figma is left aligned whereas, in mobile it is centrally aligned

**Tablet:**

1. No spacing observed below card for Tablet viewport :
2. For Android Tab, also noted that the link text is not visible

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results for this block on all viewports, Below outstanding issues are also resolved hence, marking this ticket to closed status.

**Retest Summary: Passed**:

**Desktop:**
Padding before title is 18px whereas, expected is 24px as per figma :  [SH] 18px is set as a general style and its done to keep consistency with the rest of the site
The title should be displayed on 3lines whereas, in figma it is displayed on 2lines for the same text. : [SH] the words display differently because the width is set the same width as the with-background-image to also keep it consistent.
The size for block element is shown as 485 X 696.30 px whereas, as per sigma it should be 512 X 650 px [SH] Sames as point 2
4.  The pixel size length from top should be 48px whereas, it is 75px &  pixel size length at bottom should be 38px whereas, it is 85px  [SH] the position on the bottom will differ depending on content. On top we are aligning the same as for other variations of the block
**Mobile:**
Button in Figma is left aligned whereas, in mobile it is centrally aligned   [GD] Able to see correct results now
**Tablet:**
No spacing observed below card for Tablet viewport :   [GD]  Able to see correct results now
For Android Tab, also noted that the link text is not visible [GD]  Able to see correct results now (edited) 

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/7784e5ac-0113-485e-8001-ec93bb0c6ffc">

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4dfa6c19-f63b-4709-8812-7b1953ff20cc)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2e774c59-7c03-4a59-b3f0-952d524b1d07)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/6a1e16ae-154a-4772-ab29-702cfb91ad90)
