### ISSUE TITLE
Bug: Bulldog Magazine 'Recent Articles' Block Not Dynamically Updating

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#654]
### Issue Type

Bug

### Summary

Block Name: Recent Articles (limit-10) and Recent Articles (limit-5)

### Priority

High

### Description

The Bulldog Magazine 'Recent Articles' block expected behavior is to show the most recently published articles. We are seeing 2 different errors:

1. When the Recent Articles are displayed, it is not dynamically updating to show the most recent article. The most recent article displayed in each section is a [2022 article](https://www.macktrucks.com/magazine/articles/2022/august/expertise-in-action-preview), when we have more recent content that should be displayed. 

2. In some cases, the Recent Articles do not display any articles at all. [Example](https://www.macktrucks.com/magazine/articles/2022/august/bulldog-bits-calendar-contest)

Note: This bug is happening across all Mack export sites, and the solution should be applied not only to the USA Mack site but to Australia, Mexico, etc. 

### Related Tickets

https://github.com/hlxsites/vg-macktrucks-com/issues/549
https://github.com/hlxsites/vg-macktrucks-com/issues/431

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Seems to be affected on all browsers and devices: Tested in Chrome, Edge, and Safari 

### Steps to Reproduce

1. Navigate to https://www.macktrucks.com/magazine/
2. Click on any article or category 
3. In the side bar the user will see either no articles displayed, or an older article from 2022 as the most recent article. 

Examples: 
https://www.macktrucks.com/magazine/categories/customer-profiles
https://www.macktrucks.com/magazine/articles/2022/august/bulldog-bits-calendar-contest
https://www.macktrucks.com/magazine/articles/2024/february/coastal-waste-recycling-adds-mack-lr-electric-truck-to-fleet

Note: This bug is happening across all Mack export sites, and the solution should be applied not only to the USA Mack site but to Australia, Mexico, etc. 

### Expected Results

The Bulldog Magazine 'Recent Articles' block expected behavior is to dynamically show the most recently published articles across all Mack USA and Export market sites. 

### Actual Results

Recent Articles either show no articles or keep a static article from 2022 as the most recent article - https://www.macktrucks.com/magazine/articles/2022/august/expertise-in-action-preview

### Attachment

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/61f65d57-343c-4ade-96d7-8a8d27f8d2b4)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/2da76a0c-47b6-47ba-9c56-92fc37448d33)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/d1e1c4ef-a054-4bd3-ba0b-6c40c48e84b0)

**Comment by BeckyMedlin** [comment]
@mollyaljenkins Please refine this ticket. Sorting issue may be related to this bug: See https://github.com/hlxsites/vg-macktrucks-com/issues/549

**Comment by Lakshmishri** [comment]
https://www.macktrucks.com/magazine/articles/2022/august/expertise-in-action-preview - articles are seen now
https://www.macktrucks.com/magazine/articles/2022/august/bulldog-bits-calendar-contest - the page needs to be published, articles are visible here in unpublished version https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/articles/2022/august/bulldog-bits-calendar-contest

The main problem above is the block recent article need limit. Looks like that was not provided previously because of which the articles weren't shown in some cases. Attaching an example how limit should be specified
<img width="731" alt="Screenshot 2024-03-28 at 11 17 13" src="https://github.com/hlxsites/vg-macktrucks-com/assets/4208604/b657eebb-c73c-4c12-89de-8775e961f390">

The [articles excel](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB2201E6B-8C78-4EB7-A2EB-E2A58D352468%7D&file=magazine-articles.xlsx&action=default&mobileredirect=true) file has field **lastModified**, where as the code was checking for **date**. Updated this changes in code to **lastModified**

**Comment by girishdigrajkar** [comment]
Validated and able to see the correct results hence, closing this bug:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b22cf599-8b96-4611-aacb-5c97e01748b3">


<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/0da9eeaf-33aa-4465-a760-8529a58a97b2">


<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b22cf599-8b96-4611-aacb-5c97e01748b3">
