### ISSUE TITLE
feat: Columns

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#89]
3 variations regular one porting from volvotrucks.us, (background images),(overlay images)

**Comment by jonatan-lledo-netcentric** [comment]
Columns info done

https://89-feat-columns--vg-macktrucks-com--hlxsites.hlx.page/trucks/
https://89-feat-columns--vg-macktrucks-com--hlxsites.hlx.page/trucks/anthem/

going to the next variation

**Comment by jonatan-lledo-netcentric** [comment]
Another variant finished. this one is also in the Anthem page but I create a demo page in my draft folder because I have to choose one of the 2 pics and to be sure that that is the correct one I preferred to create a draft
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/jlledo/columns/demo

the approach for the similar promo columns block will be similar if the text is in 1st column (left) and the image in the 2nd (right)

<img width="1431" alt="Screenshot 2023-05-26 at 15 57 11" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/667f808e-55fc-43df-a986-8e1ccc3eaea6">

**Comment by Andrei-Boiangiu** [comment]
with the exception of very minimal font pixels / font alignments
 this Feature has been tested with no outstanding issues
